name: skychat_server
description: The server for ... SkyChat!
# version: 1.0.0
#homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  skynet:
    path: ../skynet
  pool: ^1.5.0
  convert: ^3.0.0
  collection: ^1.15.0
  alfred: ^0.1.4+5
  sentry: ^5.1.0
  system_resources: ^1.5.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
